version = 1
SPDX-PackageName = "Friendica"
SPDX-PackageSupplier = "Friendica Project <info@friendi.ca>"
SPDX-PackageDownloadLocation = "https://friendi.ca"

[[annotations]]
path = [
     "doc/**",
     "spec/*",
     "src/**/README.md",
     "mods/**",
     ".github/ISSUE_TEMPLATE/*",
     "view/theme/frio/README.md",
     "view/theme/vier/README.md",
     "view/theme/quattro/TODO",
     "view/theme/quattro/**Makefile"
]
SPDX-FileCopyrightText = "2010-2024 The Friendica Project"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "view/lang/**/strings.php"
SPDX-FileCopyrightText = "2010-2024 The Friendica Project"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = [
     "view/theme/vier/css/font-awesome*.css",
     "view/theme/vier/css/font2.css"
]
SPDX-FileCopyrightText = "Dave Gandy"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "view/theme/vier/font/*"
SPDX-FileCopyrightText = "Dave Gandy"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "view/theme/frio/font/open_sans/**"
SPDX-FileCopyrightText = "2010 Steve Matteson, Google LLC"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "view/theme/frio/frameworks/bootstrap/**"
SPDX-FileCopyrightText = "2011-2019 Twitter, Inc."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "view/theme/frio/frameworks/bootstrap-colorpicker/**"
SPDX-FileCopyrightText = "2012 Stefan Petre"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "view/theme/frio/frameworks/bootstrap-select/**"
SPDX-FileCopyrightText = "2013-2026 bootstrap-select"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "view/theme/frio/frameworks/bootstrap-toggle/**"
SPDX-FileCopyrightText = "2014 Min Hur, The New York Times Company"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "view/theme/frio/frameworks/jasny/**"
SPDX-FileCopyrightText = "2012-2014 Arnold Daniels"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "view/theme/frio/frameworks/justifiedGallery/**"
SPDX-FileCopyrightText = "2023 Miro Mannino, Hypolite Petovan"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "view/js/fancybox/**"
SPDX-FileCopyrightText = "2019 fancyApps"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = [
     "view/theme/smoothly/js/modernizr.custom.2.5.3.*js",
     "view/js/modernizr.js"
]
SPDX-FileCopyrightText = "modernizrJS"
SPDX-License-Identifier = "MIT OR BSD-3-Clause"

[[annotations]]
path = "view/theme/frio/frameworks/jquery-scrollspy/*"
SPDX-FileCopyrightText = "2011 Samual Alexander, 2015 SoftwareSpot"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "view/theme/frio/frameworks/flexMenu/*"
SPDX-FileCopyrightText = "2012-2014 352 Inc. & Contributors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "view/theme/frio/php/PHPColors/*"
SPDX-FileCopyrightText = "Arlo Carreon"
SPDX-License-Identifier = "MIT"
