# SPDX-FileCopyrightText: 2010 - 2024 the Friendica project
#
# SPDX-License-Identifier: CC0-1.0

when:
  branch:
    exclude: [ stable ]
  event: [ pull_request, push ]

steps:
  check:
    image: fsfe/reuse:latest
    commands:
      - reuse lint
