# SPDX-FileCopyrightText: 2010 - 2024 the Friendica project
#
# SPDX-License-Identifier: CC0-1.0

name: Unit tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  tests:
    name: Unit testsuite (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        operating-system: ['ubuntu-latest']
        php: ['7.4', '8.0', '8.1', '8.2', '8.3', '8.4', '8.5']

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup PHP with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          tools: none

      - name: Clone addon repository
        run: git clone -b develop --single-branch https://git.friendi.ca/friendica/friendica-addons.git addon

      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v2"

      - name: Run Unit tests
        run: composer run test:unit